### ISSUE TITLE
Add a description for parameters

### ISSUE THREAD

**Issue by AnthonySuper** [droptheplot/apipony#1]
Basically, add a description for each parameter, to better inform users as to what it does. Ideally, of course, what a param does would be obvious by the name, but life is not always ideal. 

I already did some of the work for this in commit 65e33f8eaa51572d7ed1b6b08e5c3309f987c275 on my fork. However, I think that adding a new `td` for the description is probably going to look ugly as sin, and I couldn't actually get the specs to work on my machine (it wants me to have a `/spec/dummy/config/environment` file, which I do not have), so it's not ready to be merged quite yet.

**Comment by droptheplot** [comment]
Sorry, my bad. I added simple application to `spec/dummy` and now specs should work.
