### ISSUE TITLE
Customize the design?

### ISSUE THREAD

**Issue by connorshea** [droptheplot/apipony#2]
Is there any way we can have control over the design and layout of the API documentation pages? This looks like a really base for our API docs, but I'd like to change the color pallet, add things to the header, add our logo, etc.

**Comment by droptheplot** [comment]
Right now you can create for example `app/views/apipony/application/index.html.haml` in your application and make your design (original [here](https://github.com/droptheplot/apipony/blob/master/app/views/apipony/application/index.html.haml)).

But i think this looks ugly, I'll try to come up with something better soon.

**Comment by connorshea** [comment]
Awesome, thanks!

**Comment by connorshea** [comment]
I've rewritten [this in HTML](https://gist.github.com/connorshea/5ee68221452024bec755), for anyone interested. Not a fan of HAML, personally.

I have no expectation that this'd be adopted and used in the gem, but if you want to I can open a Pull Request.

**Comment by droptheplot** [comment]
I thought about ERB, but since I use HAML and i cannot find a tool to convert HAML to ERB, it will take a lot of time for me to keep ERB updated.

**Comment by connorshea** [comment]
I've updated all the partials to use HTML ERB [in our fork](https://github.com/noidedmedia/apipony/tree/response-description/app/views/apipony/application) while retaining mostly the same design, along with some bug fixes. I removed the custom font for simplicity's sake, although if you feel strongly about that it can be changed back.

I realize this is your project, and we don't mean to take it over, but the gem would be really useful for us to use. The problem is I'm not well-versed in HAML, and it'd be easier to recruit contributors to maintain the project over the long-term without HAML as an extra barrier-to-entry. It would also remove an extra dependency from the gem.

**Comment by AnthonySuper** [comment]
+1 on using ERB.

**Comment by droptheplot** [comment]
Ok, you're right.

**Comment by connorshea** [comment]
Awesome :D Thanks for the flexibility!

**Comment by connorshea** [comment]
I think we can close this issue now.
